name: ${project.name}
main: net.azisaba.silo.domination.Domination
version: ${project.version}
author: siloneco
description: ${project.description}
website: ${project.url}
commands:
  import:
    usage: /{LABEL} [MapName]
    aliases: ["imp"]
    permission: domination.command.import
  domination:
    usage: /{LABEL}
    aliases: ["dm"]
    permission: domination.command.domination
  chat:
    usage: /{LABEL} <public/private/toggle>
    permission: domination.command.chat
permissions:
  domination.command.import:
    default: op
  domination.game.exempt:
    default: false
  domination.command.domination:
    default: op
  domination.hide.exempt.onjoin:
    default: op
  domination.forcejoin.exempt:
    default: op
  domination.command.chat:
    default: op